kind: pipeline
name: build

globals:
  - &drone_vars 
    REG_VARIABLE: myvar
    SECRET_VARIABLE: 
      from_secret: mysecretvar
      
steps:
- name: test
  image: aquasec/trivy
  environment:
    <<: *drone_vars
    RETRIES: 0
  commands:
  - apk add --no-cache --upgrade bash
  - chmod +x ./test.sh
  - ./test.sh
