kind: pipeline
name: build

environment: 
  REG_VARIABLE: myvar
 
steps:
- name: test
  image: ubuntu:18.04
  environment:
    SECRET_VARIABLE:
    from_secret: mysecretvar
  commands:
  - RETRIES=0
  - MAX_RETRIES=2
  - until $RETRIES < $MAX_RETRIES; do let $RETRIES=$RETRIES+1; done
  - if [RETRIES == MAX_RETRIES]; then echo "Error" fi

