kind: pipeline
name: build

environment: 
  REG_VARIABLE: myvar
 
steps:
- name: test
  image: ubuntu:18.04
  environment:
    SECRET_VARIABLE:
    from_secret: mysecretvar
    RETRIES: 0
  commands:
  - until ["$RETRIES" -ge 3]; do RETRIES=$((RETRIES+1)); done
  - echo $RETRIES
