# Use this pipeline to check the formatting of Terraform and run a basic lint.
# Be sure to update your terraform image as appropriate.
# If terraform fmt fails, locally run terraform fmt -recursive to fix formatting and commit.
# The current steup will trigger for any push to a branch, including main.
kind: pipeline
name: test

steps:
  - name: check users
    image: ubuntu:latest
    commands:
    - apt-get update
    - apt-get install curl
    - curl -H "Authorization: token $GH_API" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/sawp-d/drone-demo/collaborators

trigger:
  event:
  - push
