kind: pipeline
name: build

environment: 
  REG_VARIABLE: myvar
 
steps:
- name: test
  image: ubuntu:18.04
  environment:
    SECRET_VARIABLE:
    from_secret: mysecretvar
  commands:
  - apt-get update
  - apt-get install -y gettext
  - echo $REG_VARIABLE
  - cat README.md
  - envsubst < README.md | tee README.md
  - cat README.md
  - RETRIES=0
  - MAX_RETRIES=3
  - until $RETRIES < $MAX_RETRIES; do $RETRIES+= 1; done
  - if [RETRIES == MAX_RETRIES]; then >&2 echo 'Error: Max retries exceeded for az login. Please try again.' fi

