kind: pipeline
name: build

globals:
  - &drone_vars 
    REG_VARIABLE: myvar
    SECRET_VARIABLE: 
      from_secret: mysecretvar
      
steps:
- name: test
  image: ubuntu:18.04
  environment:
    <<: *drone_vars
    RETRIES: 0
  commands:
  - mapfile -t myArray < file.txt
