kind: pipeline
name: build

environment: 
  REG_VARIABLE: myvar
  SECRET_VARIABLE:
    from_secret: mysecretvar

steps:
- name: test
  image: ubuntu:18.04
  commands:
  - echo $REG_VARIABLE
  - cat README.md
  - envsubst < README.md | tee README.md
  - cat README.md
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
